// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module rasterization2_m (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Input_1_V_V_dout,
        Input_1_V_V_empty_n,
        Input_1_V_V_read,
        Output_1_V_V_din,
        Output_1_V_V_full_n,
        Output_1_V_V_write
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] Input_1_V_V_dout;
input   Input_1_V_V_empty_n;
output   Input_1_V_V_read;
output  [31:0] Output_1_V_V_din;
input   Output_1_V_V_full_n;
output   Output_1_V_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg Input_1_V_V_read;
reg Output_1_V_V_write;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_rasterization2_odd_fu_48_ap_start;
wire    grp_rasterization2_odd_fu_48_ap_done;
wire    grp_rasterization2_odd_fu_48_ap_idle;
wire    grp_rasterization2_odd_fu_48_ap_ready;
wire    grp_rasterization2_odd_fu_48_Input_1_V_V_read;
wire   [31:0] grp_rasterization2_odd_fu_48_Output_1_V_V_din;
wire    grp_rasterization2_odd_fu_48_Output_1_V_V_write;
reg    grp_rasterization2_odd_fu_48_ap_start_reg;
wire    ap_CS_fsm_state2;
reg   [1:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 grp_rasterization2_odd_fu_48_ap_start_reg = 1'b0;
end

rasterization2_odd grp_rasterization2_odd_fu_48(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_rasterization2_odd_fu_48_ap_start),
    .ap_done(grp_rasterization2_odd_fu_48_ap_done),
    .ap_idle(grp_rasterization2_odd_fu_48_ap_idle),
    .ap_ready(grp_rasterization2_odd_fu_48_ap_ready),
    .Input_1_V_V_dout(Input_1_V_V_dout),
    .Input_1_V_V_empty_n(Input_1_V_V_empty_n),
    .Input_1_V_V_read(grp_rasterization2_odd_fu_48_Input_1_V_V_read),
    .Output_1_V_V_din(grp_rasterization2_odd_fu_48_Output_1_V_V_din),
    .Output_1_V_V_full_n(Output_1_V_V_full_n),
    .Output_1_V_V_write(grp_rasterization2_odd_fu_48_Output_1_V_V_write)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_rasterization2_odd_fu_48_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_rasterization2_odd_fu_48_ap_start_reg <= 1'b1;
        end else if ((grp_rasterization2_odd_fu_48_ap_ready == 1'b1)) begin
            grp_rasterization2_odd_fu_48_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Input_1_V_V_read = grp_rasterization2_odd_fu_48_Input_1_V_V_read;
    end else begin
        Input_1_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        Output_1_V_V_write = grp_rasterization2_odd_fu_48_Output_1_V_V_write;
    end else begin
        Output_1_V_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((grp_rasterization2_odd_fu_48_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_rasterization2_odd_fu_48_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_rasterization2_odd_fu_48_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Output_1_V_V_din = grp_rasterization2_odd_fu_48_Output_1_V_V_din;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign grp_rasterization2_odd_fu_48_ap_start = grp_rasterization2_odd_fu_48_ap_start_reg;

endmodule //rasterization2_m
