// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="rendering_m,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.118000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=77,HLS_SYN_DSP=3,HLS_SYN_FF=2900,HLS_SYN_LUT=16123,HLS_VERSION=2019_2}" *)

module rendering_m (
        Input_1_V_V,
        Output_1_V_V,
        ap_clk,
        ap_rst,
        Input_1_V_V_ap_vld,
        Input_1_V_V_ap_ack,
        Output_1_V_V_ap_vld,
        Output_1_V_V_ap_ack,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle
);


input  [31:0] Input_1_V_V;
output  [31:0] Output_1_V_V;
input   ap_clk;
input   ap_rst;
input   Input_1_V_V_ap_vld;
output   Input_1_V_V_ap_ack;
output   Output_1_V_V_ap_vld;
input   Output_1_V_V_ap_ack;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;

wire    Loop_TRIANGLES_proc1_U0_ap_start;
wire    Loop_TRIANGLES_proc1_U0_ap_done;
wire    Loop_TRIANGLES_proc1_U0_ap_continue;
wire    Loop_TRIANGLES_proc1_U0_ap_idle;
wire    Loop_TRIANGLES_proc1_U0_ap_ready;
wire    Loop_TRIANGLES_proc1_U0_Input_1_V_V_ap_ack;
wire   [31:0] Loop_TRIANGLES_proc1_U0_Output_1_V_V;
wire    Loop_TRIANGLES_proc1_U0_Output_1_V_V_ap_vld;
wire    ap_sync_continue;
wire    ap_sync_done;
wire    ap_sync_ready;
wire    Loop_TRIANGLES_proc1_U0_start_full_n;
wire    Loop_TRIANGLES_proc1_U0_start_write;

Loop_TRIANGLES_proc1 Loop_TRIANGLES_proc1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Loop_TRIANGLES_proc1_U0_ap_start),
    .ap_done(Loop_TRIANGLES_proc1_U0_ap_done),
    .ap_continue(Loop_TRIANGLES_proc1_U0_ap_continue),
    .ap_idle(Loop_TRIANGLES_proc1_U0_ap_idle),
    .ap_ready(Loop_TRIANGLES_proc1_U0_ap_ready),
    .Input_1_V_V(Input_1_V_V),
    .Input_1_V_V_ap_vld(Input_1_V_V_ap_vld),
    .Input_1_V_V_ap_ack(Loop_TRIANGLES_proc1_U0_Input_1_V_V_ap_ack),
    .Output_1_V_V(Loop_TRIANGLES_proc1_U0_Output_1_V_V),
    .Output_1_V_V_ap_vld(Loop_TRIANGLES_proc1_U0_Output_1_V_V_ap_vld),
    .Output_1_V_V_ap_ack(Output_1_V_V_ap_ack)
);

assign Input_1_V_V_ap_ack = Loop_TRIANGLES_proc1_U0_Input_1_V_V_ap_ack;

assign Loop_TRIANGLES_proc1_U0_ap_continue = 1'b1;

assign Loop_TRIANGLES_proc1_U0_ap_start = ap_start;

assign Loop_TRIANGLES_proc1_U0_start_full_n = 1'b1;

assign Loop_TRIANGLES_proc1_U0_start_write = 1'b0;

assign Output_1_V_V = Loop_TRIANGLES_proc1_U0_Output_1_V_V;

assign Output_1_V_V_ap_vld = Loop_TRIANGLES_proc1_U0_Output_1_V_V_ap_vld;

assign ap_done = Loop_TRIANGLES_proc1_U0_ap_done;

assign ap_idle = Loop_TRIANGLES_proc1_U0_ap_idle;

assign ap_ready = Loop_TRIANGLES_proc1_U0_ap_ready;

assign ap_sync_continue = 1'b1;

assign ap_sync_done = Loop_TRIANGLES_proc1_U0_ap_done;

assign ap_sync_ready = Loop_TRIANGLES_proc1_U0_ap_ready;

endmodule //rendering_m
