// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module projection_odd_m (
        ap_ready,
        input_lo_V,
        input_mi_V,
        input_hi_V,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6
);


output   ap_ready;
input  [31:0] input_lo_V;
input  [31:0] input_mi_V;
input  [31:0] input_hi_V;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
output  [7:0] ap_return_2;
output  [7:0] ap_return_3;
output  [7:0] ap_return_4;
output  [7:0] ap_return_5;
output  [7:0] ap_return_6;

wire   [7:0] tmp_fu_98_p4;
wire   [7:0] mul5_fu_112_p1;
wire   [17:0] mul5_fu_112_p2;
wire   [7:0] tmp_6_fu_128_p4;
wire   [7:0] mul2_fu_142_p1;
wire   [17:0] mul2_fu_142_p2;
wire   [7:0] tmp_7_fu_158_p1;
wire   [7:0] mul_fu_166_p1;
wire   [17:0] mul_fu_166_p2;
wire   [7:0] div2_fu_172_p4;
wire   [7:0] div_fu_118_p4;
wire   [7:0] div1_fu_148_p4;
wire   [7:0] tmp1_fu_182_p2;
wire   [7:0] triangle_3d_x0_V_fu_50_p1;
wire   [7:0] triangle_3d_y1_V_fu_74_p1;
wire   [7:0] triangle_2d_z_V_writ_fu_188_p2;
wire   [17:0] mul2_fu_142_p10;
wire   [17:0] mul5_fu_112_p10;
wire   [17:0] mul_fu_166_p10;

assign ap_ready = 1'b1;

assign ap_return_0 = triangle_3d_x0_V_fu_50_p1;

assign ap_return_1 = {{input_lo_V[15:8]}};

assign ap_return_2 = {{input_lo_V[31:24]}};

assign ap_return_3 = triangle_3d_y1_V_fu_74_p1;

assign ap_return_4 = {{input_mi_V[23:16]}};

assign ap_return_5 = {{input_mi_V[31:24]}};

assign ap_return_6 = triangle_2d_z_V_writ_fu_188_p2;

assign div1_fu_148_p4 = {{mul2_fu_142_p2[17:10]}};

assign div2_fu_172_p4 = {{mul_fu_166_p2[17:10]}};

assign div_fu_118_p4 = {{mul5_fu_112_p2[17:10]}};

assign mul2_fu_142_p1 = mul2_fu_142_p10;

assign mul2_fu_142_p10 = tmp_6_fu_128_p4;

assign mul2_fu_142_p2 = (18'd342 * mul2_fu_142_p1);

assign mul5_fu_112_p1 = mul5_fu_112_p10;

assign mul5_fu_112_p10 = tmp_fu_98_p4;

assign mul5_fu_112_p2 = (18'd342 * mul5_fu_112_p1);

assign mul_fu_166_p1 = mul_fu_166_p10;

assign mul_fu_166_p10 = tmp_7_fu_158_p1;

assign mul_fu_166_p2 = (18'd342 * mul_fu_166_p1);

assign tmp1_fu_182_p2 = (div2_fu_172_p4 + div_fu_118_p4);

assign tmp_6_fu_128_p4 = {{input_mi_V[15:8]}};

assign tmp_7_fu_158_p1 = input_hi_V[7:0];

assign tmp_fu_98_p4 = {{input_lo_V[23:16]}};

assign triangle_2d_z_V_writ_fu_188_p2 = (div1_fu_148_p4 + tmp1_fu_182_p2);

assign triangle_3d_x0_V_fu_50_p1 = input_lo_V[7:0];

assign triangle_3d_y1_V_fu_74_p1 = input_mi_V[7:0];

endmodule //projection_odd_m
